### PR TITLE
build for windows

### PR DESCRIPTION
**Pull request by DanCech**

### CODE REVIEW

**Comment by Dieterbe** [comment]
for context of what happened in nsq, see https://github.com/nsqio/nsq/pull/338
when we imported the nsq code - aug 4, 2014 via 293ca31da13647bf41428e2a60de8e0130d88b9b - it had already incorporated these changes, we just didn't copy over all files, probably because i never initially cared about windows support.
in particular we didn't copy nsqd/rename_windows.go, which at the time was the right implementation for windows (and the reason rename.go was protected with the !windows build flag is because doing that on windows resulted in all kinds of trouble, as the nsq PR explains)

However, digging a bit more through the nsq history, I found https://github.com/nsqio/nsq/commit/95dac2a3a218cfae815ac66fbfd19ba1d2c3cd3f
which shows the go stdlib now solves this for us - as of 1.5 -, so we can most likely just remove all atomic_rename stuff in favor of simply `os.Rename` and it should work fine.
I had some trouble verifying this (finding the relevant ticket or changelog)
and https://golang.org/doc/go1.5 doesn't mention this.  https://golang.org/pkg/os/#Rename mentions nothing about windows, whereas other functions have documented windows exceptions (but it doesn't mention atomicity at all?)

if you want to increase confidence, you could go through nsq's changelog to see if anything else interesting changed, or dig further into go's stdlib/docs/tickets

**Comment by DanCech** [comment]
Uh, what about the .gitignore and Makefile changes? want me to rebase this?

**Comment by DanCech** [comment]
Rebased it

**Comment by Dieterbe** [comment]
thanks Dan, sorry. moved a bit too quick on this.

**Comment by Dieterbe** [comment]
merged :+1:

**Pull request closed without merging**
