### PR TITLE
Add ability to write out pidfile

### PR DESCRIPTION
**Pull request by lwf**

### CODE REVIEW

**Comment by lwf** [comment]
Amended with more reasonable example config defaults.

**Comment by Dieterbe** [comment]
what's the use of this? do you leverage this in an init script? (which? can you also contribute that?)

**Comment by lwf** [comment]
Yes, we have an init script which we use this for. I'll clean it up a bit and add it as well.

**Comment by Dieterbe** [comment]
ping?

**Comment by lwf** [comment]
Hey,

Getting back to this now post vacation. The init script is ready to be contributed and I'd like to rebase this on top of latest HEAD, but I'm having trouble building as per #84. I'll get back to this once I have it sorted.

**Comment by lwf** [comment]
Rebased and added init script.

**Pull request merged**
