### PR TITLE
Use useradd to support multiple distros

### PR DESCRIPTION
**Pull request by Duologic**
See https://github.com/graphite-ng/carbon-relay-ng/issues/232

I would make a pull request but I don't have RedHat installation ready to test. Anyone who can output me useradd --help and adduser --help from RedHat?

I checked these man pages for this change:
* https://linux.die.net/man/8/adduser
* https://linux.die.net/man/8/useradd

### CODE REVIEW

**Comment by AnderEnder** [comment]
Centos7
```
$ docker run -it centos:7 /bin/bash
[root@1c425a61e283 /]# adduser --help
Usage: adduser [options] LOGIN
       adduser -D
       adduser -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account
  -d, --home-dir HOME_DIR       home directory of the new account
  -D, --defaults                print or change default useradd configuration
  -e, --expiredate EXPIRE_DATE  expiration date of the new account
  -f, --inactive INACTIVE       password inactivity period of the new account
  -g, --gid GROUP               name or ID of the primary group of the new
                                account
  -G, --groups GROUPS           list of supplementary groups of the new
                                account
  -h, --help                    display this help message and exit
  -k, --skel SKEL_DIR           use this alternative skeleton directory
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -l, --no-log-init             do not add the user to the lastlog and
                                faillog databases
  -m, --create-home             create the user's home directory
  -M, --no-create-home          do not create the user's home directory
  -N, --no-user-group           do not create a group with the same name as
                                the user
  -o, --non-unique              allow to create users with duplicate
                                (non-unique) UID
  -p, --password PASSWORD       encrypted password of the new account
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             login shell of the new account
  -u, --uid UID                 user ID of the new account
  -U, --user-group              create a group with the same name as the user
  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping
```
Rhel7:

```
docker run -it richxsl/rhel7 /bin/bash
Unable to find image 'richxsl/rhel7:latest' locally
latest: Pulling from richxsl/rhel7
1de5db95c595: Pull complete
Digest: sha256:8f3aae325d2074d2dc328cb532d6e7aeb0c588e15ddf847347038fe0566364d6
Status: Downloaded newer image for richxsl/rhel7:latest
[root@c347a00ffa35 /]# adduser --help
Usage: adduser [options] LOGIN
       adduser -D
       adduser -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account
  -d, --home-dir HOME_DIR       home directory of the new account
  -D, --defaults                print or change default useradd configuration
  -e, --expiredate EXPIRE_DATE  expiration date of the new account
  -f, --inactive INACTIVE       password inactivity period of the new account
  -g, --gid GROUP               name or ID of the primary group of the new
                                account
  -G, --groups GROUPS           list of supplementary groups of the new
                                account
  -h, --help                    display this help message and exit
  -k, --skel SKEL_DIR           use this alternative skeleton directory
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -l, --no-log-init             do not add the user to the lastlog and
                                faillog databases
  -m, --create-home             create the user's home directory
  -M, --no-create-home          do not create the user's home directory
  -N, --no-user-group           do not create a group with the same name as
                                the user
  -o, --non-unique              allow to create users with duplicate
                                (non-unique) UID
  -p, --password PASSWORD       encrypted password of the new account
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             login shell of the new account
  -u, --uid UID                 user ID of the new account
  -U, --user-group              create a group with the same name as the user
  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping
```

**Comment by Dieterbe** [comment]
so is this ready for review or do you want to tweak further?

**Comment by Duologic** [comment]
As mentioned in the linked issue, I need to check this against Debian.

**Comment by Duologic** [comment]
I was assuming a bit that there would be a difference between rhel's and centos' `adduser`, but that doesn't seem the case. The current line in `after_install.sh` is apparently tailored to the [debian](https://manpages.debian.org/stretch/adduser/adduser.8.en.html)/[ubuntu](http://manpages.ubuntu.com/manpages/zesty/en/man8/adduser.8.html) `adduser`.

It looks like the `useradd` command is the common denominator between these 4.
- adduser is a symbolic link for useradd on [rhel/centos](https://www.linuxquestions.org/questions/linux-enterprise-47/what-is-difference-b-t-useradd-and-adduser-742726/)
- https://manpages.debian.org/stretch/passwd/useradd.8.en.html
- http://manpages.ubuntu.com/manpages/zesty/en/man8/useradd.8.html

I'll rewrite the `after_install.sh` to use `useradd` then and see from there.

**Comment by Duologic** [comment]
There we go, review that code! ☺️

**Comment by Dieterbe** [comment]
LGTM. thanks!

**Pull request merged**
