### PR TITLE
CloudWatch route added

### PR DESCRIPTION
**Pull request by Mexx77**
* New route to AWS metric service CloudWatch added
* Uses the AWS CloudWatch Go-SDK
* Tested successfully at my company
* Since highly integrated, I didn't come up with a meaningful unit test (but open for proposals)
* Did, however, lots of manual integration tests within the AWS cloud.

### CODE REVIEW

**Comment by Mexx77** [comment]
It should not have side effects on other components of carbon-relay-ng. Any suggestions of things we can improve before a merge?

**Comment by Dieterbe** [comment]
LGTM. thanks @Mexx77

**Comment by Dieterbe** [comment]
Hi @Mexx77 this broke the build due to the library not being included in the vendor folder.
i pulled down the latest version (v1.13.24) but still don't get it to compile:
```
~/g/s/g/g/carbon-relay-ng ❯❯❯ make build
cd ui/web && go-bindata -pkg web admin_http_assets
find . -name '*.go' | grep -v '^\.\/vendor' | xargs gofmt -w -s
CGO_ENABLED=0 go build -ldflags "-X main.Version=0.9.4-31-g32eadce" ./cmd/carbon-relay-ng
vendor/github.com/aws/aws-sdk-go/aws/types.go:7:2: use of internal package not allowed
make: *** [Makefile:7: build] Error 1


~/g/s/g/g/carbon-relay-ng ❯❯❯ go test -v -race $(go list ./... | grep -v /vendor/)
vendor/github.com/aws/aws-sdk-go/aws/types.go:7:2: use of internal package not allowed
```

please advise thanks.

**Comment by Mexx77** [comment]
I will look into that soon.

**Comment by Mexx77** [comment]
I ran `govendor fetch github.com/aws/aws-sdk-go@v1` which made this update to vendor/vendor.json:
```
                {
+                       "checksumSHA1": "2fRYV/6rmBLWiVrmVF/bPFIqMEA=",
+                       "path": "github.com/aws/aws-sdk-go",
+                       "revision": "4b5324816e154564ef4e490842c2e40560971f75",
+                       "revisionTime": "2018-03-29T22:31:01Z",
+                       "version": "v1",
+                       "versionExact": "v1.13.24"
+               },
```

build works on my Ubuntu machine now: `make build`
```
cd ui/web && go-bindata -pkg web admin_http_assets
find . -name '*.go' | grep -v '^\.\/vendor' | xargs gofmt -w -s
CGO_ENABLED=0 go build -ldflags "-X main.Version=0.9.4-31-g32eadce" ./cmd/carbon-relay-ng
```
I am not sure how your vendoring process works. Shall I commit my vendor/vendor.json now to my fork?

**Comment by Dieterbe** [comment]
which version of go do you use?
they started enforcing the `internal` rules with go 1.5 I think.
https://golang.org/doc/go1.5#go_command

please confirm whether you can build with a recent go version like 1.9 or 1.10

**Comment by Mexx77** [comment]
go version go1.10 linux/amd64

**Comment by Dieterbe** [comment]
huh, strange. anyway if you can add the dependency and get it to build, please file that as a PR here, i'll see if i can build it too.

**Comment by Mexx77** [comment]
just the updated vendor.json, right?

**Comment by Dieterbe** [comment]
also all the aws stuff within the vendor dir.

**Comment by Mexx77** [comment]
done. sorry for not having it done in the first place. was all in my gopath :/. Now all I did to add the dependencies was:

```
govendor fetch github.com/aws/aws-sdk-go@v1
govendor fetch github.com/aws/aws-sdk-go/aws@v1
...
```
and for a few sub-packaged of aws that were missiing when I ran make build.
Weird that govendor keeps a copy of every dependency and that they are checked in - in my opinion
have a good evening!

**Comment by Dieterbe** [comment]
FWIW, govendor manages the vendor directory, but the principle of checking in the dependencies into git, is something we (I) decided to do, in order to guarantee consistent builds everywhere.
there's a lot of discussion about pro's and cons to that approach. it will probably change soon anyway, it sounds like go will adopt vgo (https://blog.golang.org/versioning-proposal)

**Pull request merged**
