### PR TITLE
listen for UDP

### PR DESCRIPTION
**Pull request by jschlichtholz**
Add listener for UDP datagrams.

See graphite-ng/carbon-relay-ng#78

Those are the first lines of go I wrote so any review / testing is really appreciated!

### CODE REVIEW

**Comment by Dieterbe** [comment]
Did you test both udp and tcp input with this applied?

**Comment by jschlichtholz** [comment]
I had no graphite available so testing was limited to a `tail -f` on the spool file. But both, TCP and UDP worked even when sending metrics via both protocols in parallel.

**Comment by jschlichtholz** [comment]
I just retested this using a "real" graphite backend and an own application. Looks like TCP and UDP are working fine. I would like to see someone else verifying this nonetheless.

**Comment by Dieterbe** [comment]
oh sorry i forgot to merge this.
looks good to me! fastest way to get people to test it is to merge it :)

**Pull request merged**
