### PR TITLE
Add support of hashing route algorithm

### PR DESCRIPTION
**Pull request by vladimir-smirnov-sociomantic**
It's simple and fast, using crc32 to determine which connection to use.

### CODE REVIEW

**Comment by blysik** [comment]
Another vote here for making it a drop in replacement for Carbon's consistent hashing.  I use that in production right now, and would switch to carbon-relay-ng if I didn't have to migrate my existing CH metrics around.

**Comment by blysik** [comment]
Starting to look at how carbon-relay does CH here: https://github.com/graphite-project/carbon/blob/master/lib/carbon/hashing.py

**Comment by blysik** [comment]
And then this bit in routers.py:

def getDestinations(self, metric):
    key = self.getKey(metric)

    for count,node in enumerate(self.ring.get_nodes(key)):
      if count == self.replication_factor:
        return
      (server, instance) = node
      port = self.instance_ports[ (server, instance) ]
      yield (server, port, instance)

getKey just returns the metric as the key.  carbon-relay-ng would have to know the replication factor being used, to copy carbon's CH function.

**Comment by Dieterbe** [comment]
i'm going to close this until we have a consistent hashing implementation as discussed above.

**Pull request closed without merging**
