### PR TITLE
Embed external web dependencies

### PR DESCRIPTION
**Pull request by efficks**
Embed bootstrap, angular, jquery and more in carbon-relay-ng to be able to use the admin web page in a closed network.
Fix issue #87

### CODE REVIEW

**Comment by Dieterbe** [comment]
can you share the steps taken to create this PR,
e.g. which bootstrap/angular downloads you've used, which bindata command you've run, etc
i want to check that everything looks allright.
PS: thanks!

**Comment by efficks** [comment]
@Dieterbe 
I've download all external files pointed by index.html by copying all URL from it in a wget command.

- https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
- https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css
- https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js
- https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
- https://code.angularjs.org/1.2.10/angular.min.js
- https://code.angularjs.org/1.2.10/angular-resource.min.js
- https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap-tpls.js
- https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js
- https://oss.maxcdn.com/respond/1.4.2/respond.min.js

Maybe we should eventually download all these files automatically.

**Comment by Dieterbe** [comment]
Hey @efficks, sorry it took me a while to get back to this.
for security reasons i've redownloaded all the new files and confirmed they are all legit.
also the file admin_http_assets/fonts/glyphicons-halflings-regular.woff

i've also rebased on top of master -> #371

**Comment by Dieterbe** [comment]
thanks for your contribution! this is now merged via #371

**Pull request closed without merging**
