### PR TITLE
Implement AMQP input

### PR DESCRIPTION
**Pull request by jnjackins**
For #159. I have done some minimal testing and it seems to work as expected; please let me know what you think of my approach before I do more rigorous testing.

### CODE REVIEW

**Comment by Dieterbe** [comment]
Hey Jeremy, this looks spot on. the code looks good, the config looks good, you vendored the dependency

So does the default settings match how graphite/carbon does it? So it's basically plug and play?

Is any documentation required? If so, could add a amqp section to the readme.

**Comment by jnjackins** [comment]
Hi @Dieterbe, great to hear. Yes, this should be more or less how it works in the default carbon daemons; the configuration options I added mostly match up with the ones available there. Here is our configuration, for consuming metrics put on the "metrics" exchange by sensu:

```
ENABLE_AMQP = True
# AMQP_VERBOSE = False
AMQP_HOST = redacted
AMQP_PORT = 5672
AMQP_VHOST = /sensu
AMQP_USER = sensu
AMQP_PASSWORD = redacted
AMQP_EXCHANGE = metrics
AMQP_METRIC_NAME_IN_BODY = True
```

The exception is AMQP_METRIC_NAME_IN_BODY. I'm not familiar with how this would work *without* the metric name in the message body, so I left that out (I'm sure someone could easily add that later on).

I will add some documentation to the readme.

One thing that still concerns me: as-is, the AMQP consumer goroutine will cause the program to exit in the event of e.g. the queue being closed, which is outside of our control. I think the body of the StartAMQP function should be wrapped in a for loop, printing a warning and perhaps doing some exponential backoff in case the error is unrecoverable. Or perhaps a better option would be to simply disable the AMQP consumer and let everything else run as normal after N failures within some interval. Do you have any thoughts on that?

**Comment by Dieterbe** [comment]
oops yeah if that happens, better to retry with an exponential backoff like you say.
FWIW I found 	"github.com/jpillora/backoff" quite useful, you can see it being used in route/grafananet.go
I think it's a good idea to keep retrying forever and never give up.

**Comment by jnjackins** [comment]
Added backoff, please take another look.

Sample:
```
08:39:21.759906 ▶ NOTI  dialing AMQP: amqp://localhost/
08:39:21.762541 ▶ NOTI  admin TCP listener starting on 0.0.0.0:2004
08:39:21.774886 ▶ ERRO  connectAMQP: Exception (404) Reason: "NOT_FOUND - no exchange 'metrics' in vhost '/'"
08:39:21.774934 ▶ INFO  retrying in 500ms
08:39:22.278774 ▶ NOTI  dialing AMQP: amqp://localhost/
08:39:22.288095 ▶ ERRO  connectAMQP: Exception (404) Reason: "NOT_FOUND - no exchange 'metrics' in vhost '/'"
08:39:22.288173 ▶ INFO  retrying in 1s
08:39:23.291537 ▶ NOTI  dialing AMQP: amqp://localhost/
08:39:23.301057 ▶ ERRO  connectAMQP: Exception (404) Reason: "NOT_FOUND - no exchange 'metrics' in vhost '/'"
08:39:23.301092 ▶ INFO  retrying in 2s
08:39:25.304943 ▶ NOTI  dialing AMQP: amqp://localhost/
08:39:25.314634 ▶ ERRO  connectAMQP: Exception (404) Reason: "NOT_FOUND - no exchange 'metrics' in vhost '/'"
08:39:25.314664 ▶ INFO  retrying in 4s
```

**Comment by jnjackins** [comment]
Added a new section to the README.

**Comment by Dieterbe** [comment]
oh i see you added the dependency as a git submodule? Please don't do that. you can just use `govendor add <package path>` and it'll bring in the files. We keep the actual source code directly in the vendor dir.
otherwise looks great!

**Comment by jnjackins** [comment]
Oops, thought I had fixed that already. Please take another look.

**Comment by Dieterbe** [comment]
nice work @jnjackins , thank you!

**Comment by jnjackins** [comment]
Cheers!
Closes #159

**Pull request merged**
