### PR TITLE
Fix the creation of `/var/run/carbon-relay-ng` directory (#212)

### PR DESCRIPTION
**Pull request by guillaumeautran**
Fix tmpfiles directory ownership

### CODE REVIEW

**Comment by Dieterbe** [comment]
hmm wouldn't it be better to just use carbon-relay-ng user and group in the packages?

examples/carbon-relay-ng.init currently stipulates:
```
27:[ -z "$RELAY_USER" ] && RELAY_USER="carbon-relay-ng"
28:[ -z "$RELAY_GROUP" ] && RELAY_GROUP="carbon-relay-ng"
```
(but i'm not sure if this is used anywhere)
the fpm targets in the makefile don't seem to specify a user/group.

**Comment by guillaumeautran** [comment]
I was not sure really if the user was actually used. I can make the change to add a system user `carbon-relay-ng` and make use of it. None of the TCP ports used are privilege so it should be good. The  PID file might need fixing but I'll take care of that.

**Comment by guillaumeautran** [comment]
Note that the systemd unit file starts carbon as the root user...

**Comment by guillaumeautran** [comment]
Ok, I've fixed the patch to make use (and create) the `carbon-relay-ng` user and group. Tested it on Ubuntu platform (Xenial + systemd). Don't have access to other platforms right now so if anyone wants to do a quick validation for me. That would be much appreciated!

**Comment by guillaumeautran** [comment]
Ping?

**Comment by Dieterbe** [comment]
sorry for the late reaction, but looks good. thanks Guillaume!

**Pull request merged**
