### PR TITLE
Stop leaking go routines

### PR DESCRIPTION
**Pull request by replay**
fixes issue https://github.com/graphite-ng/carbon-relay-ng/issues/315

### CODE REVIEW

**Comment by Dieterbe** [comment]
looks perfect to me.
do a quick test and we can merge

**Comment by replay** [comment]
Tested as following:

* Starting CRNG and pointing it at a local `nc -l`. Grepping for `listen.go:140` in its output, because once i send it `SIGQUIT` it will dump a stack trace and if there's a go routine waiting at the specific place which this PR fixes then there should be a line at `listen.go:140` in that trace:
```
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ ./carbon-relay-ng carbon-relay-ng.ini.dev-nc 2>&1 | grep listen.go:140
```
* Sending some data into the CRNG with `telnet` and verifying that it comes out in my `nc -l`, to make sure everything is connected:
```
mst@mst-nb1:~$ telnet localhost 2013
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
replaytest.abc 123 123

# other terminal
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ nc -l -p 20004 | grep replaytest
replaytest.abc 123 123
```
* Sending `SIGQUIT` to CRNG, without closing my telnet client connection, to verify that this go routine shows up in the trace:
```
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ ./carbon-relay-ng carbon-relay-ng.ini.dev-nc 2>&1 | grep listen.go:140
	/home/mst/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng/input/listen.go:140 +0x10e
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ 
```
* Now I start CRNG again, and again I connect with `telnet` and send some data through it to verify that everything is connected. Then i close my `telnet` session before sending `SIGQUIT` to CRNG. This time there should not be any goroutine hanging at `listen.go:140`:
```
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ ./carbon-relay-ng carbon-relay-ng.ini.dev-nc 2>&1 | grep listen.go:140
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ 
```

**Comment by Dieterbe** [comment]
clever

**Comment by woodsaj** [comment]
@replay using your testing method were you able to verify that goroutines were leaking?

**Comment by replay** [comment]
@woodsaj 
This is on the version without this PR:

* I disabled instrumentation to make crng not connect to its own input port
* Then I started it while grepping for `listen.go:132`, because that's where this go routine is waiting in this version of the code. After waiting a min without any activity and then sending it `SIGQUIT` there is no single line at `listen.go:132`:
```
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ ./carbon-relay-ng carbon-relay-ng.ini.dev-nc 2>&1 | grep listen.go:132
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ 
```
* Then I started it again in the same way. Created `3` telnet connections and closed each of them again. Then I sent `SIGQUIT` again:
```
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ ./carbon-relay-ng carbon-relay-ng.ini.dev-nc 2>&1 | grep listen.go:132
	/home/mst/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng/input/listen.go:132 +0x38
	/home/mst/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng/input/listen.go:132 +0x38
	/home/mst/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng/input/listen.go:132 +0x38
mst@mst-nb1:~/documents/code/go/src/github.com/graphite-ng/carbon-relay-ng$ 

```

**Pull request merged**
