### PR TITLE
Add GOMAXPROCS setting to allow further threading

### PR DESCRIPTION
**Pull request by johnseekins**
Simple change, but it should allow this program to thread more.

### CODE REVIEW

**Comment by Dieterbe** [comment]
looks good, but could you make the param confirm to the style ("max_procs") and run gofmt -w on the code.

**Comment by johnseekins** [comment]
Better?

**Comment by johnseekins** [comment]
This does, annecdotally, show some pretty significant performance improvement.

**Comment by Dieterbe** [comment]
i disagree with the comment in the ini.
this is useful in various scenarios beyond just hyperthreading, which is an intel specific implementation.
also i'm suspicious of the num_cores*2 recommendation.
have you measured that performing better than max_procs = num_cores or num_cores +1 ?

**Comment by johnseekins** [comment]
That comment was from a colleague who helps with Heka development. He kept talking about hyper-threading as a kernel thing, not a processor thing.
I'll take it out.

**Comment by Dieterbe** [comment]
looks good now thanks

**Comment by johnseekins** [comment]
Woo! My first merge on a Go project!

**Comment by Dieterbe** [comment]
:+1:

**Pull request merged**
